### ISSUE TITLE
CalVer Bumping Doesn't Bump

### ISSUE THREAD

**Issue by sco1** [sco1/bumper#9]
Well I thought I had tested #8 enough but turns out I didn't...whoopsie

Trying out on a live project results in an empty diff:

Sample `.bumper.toml`:
```toml
[tool.bumper]
current_version = "2025.05.0"
versioning_type = "calver"

[[tool.bumper.files]]
file = "./pyproject.toml"
search = 'version = "{current_version}"'
```

Sample `pyproject.toml`:
```toml
[project]
name = "some-calver-project"
version = "2025.05.0"
```

The results:

```
$ bumper bump date --dry-run



$ 
```
